### ISSUE TITLE
© instead of р

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ceesaxp/as-convert-russian#6] opened 2015-03-14 15:16 UTC
```
For some reason, I get the © character when it should be an р (Russian "r"). 
Weird.

Thanks for this tool! The issue has been bugging me for a long time, and I 
never figured out the 
solution!!
```

Original issue reported on code.google.com by `eugene.v...@gmail.com` on 30 May 2010 at 3:03

**Comment by pvoznenko** [comment] 2015-07-04 08:17
Using script now, and could not reproduce reported bug. I @Ceesaxp you can close this one.

**Closed** 2016-07-17 19:55 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
